### ISSUE TITLE
Android App crash 

### ISSUE THREAD

**Issue by balwinders** [trietho/react-native-a-beep#16]
Fatal Exception: java.lang.RuntimeException: Init failed
       at android.media.ToneGenerator.native_setup(ToneGenerator.java)
       at android.media.ToneGenerator.<init>(ToneGenerator.java:746)
       at com.trietho.RNReactNativeABeepModule.<init>(RNReactNativeABeepModule.java:14)
       at com.trietho.RNReactNativeABeepPackage.createNativeModules(RNReactNativeABeepPackage.java:16)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
       at java.lang.Thread.run(Thread.java:764)

**Comment by tudiantuan** [comment]
i have same issue when update android 11

**Comment by Productivix** [comment]
hi, yes crash on And 7 : red screen title "Init failed"
native_setup Tonegenerator.java
748
I had put in the stack but not calling it in the program
